[package]
name = "rf64"
version = "1.0.0"
description = "Rust-based bare-metal firmware for the DJTechTools MIDI Fighter 64 controller."
license = "AGPL-3.0"
edition = "2024"
authors = ["zeph <https://github.com/ZephyrCodesStuff>"]
repository = "https://github.com/ZephyrCodesStuff/rf64"
keywords = ["embedded", "avr", "midi", "usb", "atmega32u4"]
categories = ["embedded", "usb", "midi"]

[features]
default = ["boot-anim", "apollo"]
boot-anim = []
keyboard = []
apollo = []
mystrix = []

[dependencies]

# Atmel AVR abstractions
avr-device = { version = "0.8.1", features = ["atmega32u4"] }
atmega-hal = { git = "https://github.com/rahix/avr-hal", branch = "main", features = [
    "atmega32u4",
    "rt",
] }
avr-progmem = "0.4.0"

# USB stack
atmega-usbd = { git = "https://github.com/ZephyrCodesStuff/atmega-usbd", branch = "master" }
usb-device = "0.2.9"
usbd-midi = "0.1.0"
