name: Clippy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clippy:
    name: Run cargo clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install AVR Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-avr avr-libc binutils-avr

      - name: Install Rust Nightly Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, clippy

      - name: Ensure rust-src component
        run: rustup component add rust-src

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo clippy (deny warnings + nursery)
        run: |
          cargo clippy --bins --release -- -D warnings -D clippy::nursery
